version: '3'

services:
  web:
    build: .
    restart: always    # Agregado aquí
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_ERROR_REPORTING=E_ALL
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always    # Agregado aquí
    ports:
      - "127.0.0.1:3306:3306"    # Modificado aquí
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miapp
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d    # Agrega esta línea
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data: