version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./:/var/www/html:cached
      - app_logs:/var/www/html/application/logs
      - app_cache:/var/www/html/application/cache
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_ERROR_REPORTING=E_ALL
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miapp
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  app_logs:
  app_cache: